# Site wide configuration

title: #Reshmi Ghosh
description: Hello! Welcome to my webpage
show_downloads: false


locale: en_US
url: https://reshmighosh.github.io
# Jekyll configuration
theme: minimal-mistakes-jekyll

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Site owner
owner:
  name: Reshmi Ghosh
  avatar: 1462696_10200387915380867_283294306_o.jpeg #try image instead of avatar, try cmlh pic
  position: Graduate Student
  school: Carnegie Mellon University
  place: Pittsburgh, PA.
  bio: "Ph.D. student<br/> Carnegie Mellon University&#13;&#10;Pittsburgh, PA"
  email: reshmig@andrew.cmu.edu

  twitter: reshmigh

  github: reshmighosh

  linkedin: reshmi-ghosh #username
 

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]



