# Site wide configuration
theme: jekyll-theme-minimal
title: Reshmi Ghosh
description: Ph.D. student, Carnegie Mellon University
show_downloads: false
logo: /images/1462696_10200387915380867_283294306_o.jpeg
