# Site wide configuration
theme: jekyll-theme-minimal
title: Reshmi Ghosh
description: Ph.D. Applied Scientist, Microsoft (Office of Applied Research)
show_downloads: false
logo: /images/1462696_10200387915380867_283294306_o.jpeg
twitter: reshmighosh
github: reshmighosh

